#!/bin/sh
### BEGIN INIT INFO
# Provides:          simon 
# Required-Start:   
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop simon 
### END INIT INFO

# Change this PATH if you need
SIMON="/opt/simon/simon.sh"

test -f $SIMON || exit

case "$1" in
start)
        $SIMON &
                echo "* Starting simon scripts" 
    ;;
stop)
        PID=`ps -C simon.sh -opid=`
        kill $PID
                echo "* Stoping simon scripts"
        ;;
restart)
        $0 stop
        $0 start
    ;;
esac
