#!/bin/sh
### BEGIN INIT INFO
# Provides:          simon 
# Required-Start:   
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop simon web server
### END INIT INFO


SYS_CHECK=/opt/simon/simon.sh

test -f /opt/simon/simon.sh || exit

case "$1" in
start)
        /opt/simon/simon.sh &
    ;;
stop)
        PID=`ps -C simon.sh -opid=`
        kill $PID
        ;;
restart)
        $0 stop
    	$0 start
    ;;
esac
